import {type FC, useEffect} from "react"
import Head from "next/head";
import {useRouter} from "next/router";


const EndGame: FC = () => {
    const router = useRouter();
    const score = router.query.score;

    // moving the useRouter hook inside a useEffect hook, making sure that the useRouter hook is only called after the component has mounted
    // Otherwise, checks for undefined ran on the server, where router.push isn't available.
    useEffect(() => {
        if (score === undefined) {
            void router.push({
                pathname: '/404',
            });
        }
    }, [router, score]);

    console.log(score)
    return(
        <>
            <Head>
                <title> Quizzical 2 </title>
                <meta name="description" content = "generated by create-t3-app" />
                <link rel = "icon" href= "/favicon.ico" />
            </Head>
            <main className="flex h-screen">
                <div className="m-auto text-center max-w-5xl " >
                    <h1 className="text-5xl pt-6 text-indigo-500 font-bold m-2 ">Congratulations!</h1>
                    <h2 className="text-xl pt-6 font-bold m-2 text-green-300">You scored: {score} out of 5 </h2>
                    <button className="text-white bg-green-600 text-lg p-2 rounded-full transition hover:bg-green-700 w-44 text-base font-semibold mt-5" type="button" onClick={() => void router.push("/")}>
                        Play again!
                    </button>
                </div>
            </main>
    </>
    )
}

export default EndGame