import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { api } from "~/utils/api";
import {useRouter} from "next/router";

const Home: NextPage = () => {
    const router = useRouter()

    async function handleGameStart(gamemode:string){
        router.push({
            pathname:"/questionDisplay",
            query:{
                gamemode:gamemode
            }
        })
    }

  return (
    <>
      <Head>
        <title> Quizzical 2 </title>
        <meta name="description" content = "generated by create-t3-app" />
        <link rel = "icon" href= "/favicon.ico" />
      </Head>

      <main>
          <div className="flex h-screen ">
              <div className="m-auto">
                  <div className="text-indigo-500 text-center">
                      <h1 className="text-5xl align-middle font-extrabold">Quizzical</h1>
                      <h3 className="text-xl pt-6 font-bold">A quiz game with different questions each time you play!</h3>
                      <h3 className="pt-6 text-lg font-bold">Select a difficulty below to get started!</h3>
                      <div className="m-auto space-x-4 mt-2 ">
                          <button className="text-white bg-green-600 text-sm p-2 rounded-full transition hover:bg-green-700 w-44 text-base font-semibold " type="button" onClick={(() => handleGameStart("Easy"))} >Easy</button>
                          <button className="text-white bg-orange-600 text-sm p-2 rounded-full transition hover:bg-orange-700 w-44 text-base font-semibold " type="button">Medium</button>
                          <button className="text-white bg-red-600 text-sm p-2 rounded-full transition hover:bg-red-700 w-44 text-base font-semibold" type="button">Extreme</button>
                      </div>
                      <h3 className="text-xl pt-6 font-bold">Or, play from one of the following preselected categories!</h3>
                      <div className="m-auto space-x-4 mt-2 ">
                          <button className="text-white bg-pink-600 text-sm p-2 rounded-full transition hover:bg-pink-700 w-44 text-base font-semibold " type="button">80's Trivia</button>
                          <button className="text-white bg-cyan-500 text-sm p-2 rounded-full transition hover:bg-cyan-600 w-44 text-base font-semibold " type="button">Sport</button>
                          <button className="text-white bg-purple-600 text-sm p-2 rounded-full transition hover:bg-purple-700 w-44 text-base font-semibold" type="button">Music</button>
                          <button className="text-white bg-gray-600 text-sm p-2 rounded-full transition hover:bg-gray-700 w-44 text-base font-semibold" type="button">Film & TV</button>
                      </div>
                      <h3 className="pt-6 text-lg font-bold">Average Score:</h3>
                      <button className="text-white bg-gray-700 text-sm p-2 rounded-full transition hover:bg-gray-800 w-56 h-11 text-base font-semibold" type="button">Settings</button>

                  </div>
              </div>
          </div>

      </main>

    </>
  );
};

export default Home;




