import {GetServerSideProps, GetServerSidePropsContext, InferGetServerSidePropsType, NextPage} from "next";
import Home from "~/pages/index";
import axios from 'axios';
import AnswerButtons from "~/components/answerButtons";
import Head from "next/head";
import {useState} from "react";

interface questionType {
    question: string,
    correctAnswer: string,
    incorrectAnswers: string[],
    difficulty: string,
}

const QuestionDisplay: NextPage< InferGetServerSidePropsType<typeof getServerSideProps>> = ({questions}) => {
    const [score,setScore] = useState<number>(0)

    const handleAnswerButtonClick = (isCorrect:boolean) => {
        if(isCorrect){setScore(prevState => prevState + 1)}
    }

    return(
        <>
            <Head>
                <title> Quizzical 2 </title>
                <meta name="description" content = "generated by create-t3-app" />
                <link rel = "icon" href= "/favicon.ico" />
            </Head>

            <main className="flex h-screen">
                <div className="m-auto" >
                    {questions.map((question:questionType) => {
                        return(
                            <div className="text-center">
                                <h1 className="text-xl pt-6 text-indigo-500 font-bold m-2 ">{question.question}</h1>
                                <AnswerButtons correctAnswer={question.correctAnswer} incorrectAnswers={question.incorrectAnswers} onAnswerClicked={handleAnswerButtonClick}/>
                            </div>
                        )
                    } )}
                </div>

            </main>
        </>
    )
}

export const getServerSideProps: GetServerSideProps = async (context:GetServerSidePropsContext) => {

    let questions = null

    await axios.get("https://the-trivia-api.com/api/questions?limit=5&difficulty=easy").then(res => questions = res.data)


    console.log(questions)
    return({
        props:{
            questions:questions
        }
    })

}

export default QuestionDisplay;
